const pokemonTypes = {
    bug: { src: "./assets/bug.svg", colour: "#80ba5b" },
    dark: { src: "./assets/dark.svg", colour: "#565755" },
    dragon: { src: "./assets/dragon.svg", colour: "#29419e" },
    electric: { src: "./assets/electric.svg", colour: "#ffdd03" },
    fairy: { src: "./assets/fairy.svg", colour: "#f57df3" },
    fighting: { src: "./assets/fighting.svg", colour: "#c72c48" },
    fire: { src: "./assets/fire.svg", colour: "#ed9118" },
    flying: { src: "./assets/flying.svg", colour: "#c4f6ff" },
    ghost: { src: "./assets/ghost.svg", colour: "#364a78" },
    grass: { src: "./assets/grass.svg", colour: "#24e307" },
    ground: { src: "./assets/ground.svg", colour: "#b0593a" },
    ice: { src: "./assets/ice.svg", colour: "#15eddb" },
    normal: { src: "./assets/normal.svg", colour: "#8c8c8c" },
    poison: { src: "./assets/poison.svg", colour: "#a262f0" },
    psychic: { src: "./assets/psychic.svg", colour: "#f2acb8" },
    rock: { src: "./assets/rock.svg", colour: "#b0a67d" },
    steel: { src: "./assets/steel.svg", colour: "#5c8194" },
    water: { src: "./assets/water.svg", colour: "#0066ff" },
};
export default pokemonTypes;
